# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/kshinpad/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#import Matugen colors (generated by matugen — updates with wallpaper)
[ -f ~/.config/matugen/zsh_colors.sh ] && source ~/.config/matugen/zsh_colors.sh

#proxy

#export http_proxy="http://172.16.2.251:3128"
#export https_proxy="http://172.16.2.251:3128"
#export ftp_proxy="http://172.16.2.251:3128"

#aliases

alias z="vim ~/.zshrc"
alias n="cd ~/Documents/notes"

#terminal prompt — managed by starship
eval "$(starship init zsh)"

export EDITOR=vim

#qt theming
export QT_QPA_PLATFORMTHEME=qt6ct

export VISUAL=code

[ -f "/home/kshinpad/.ghcup/env" ] && . "/home/kshinpad/.ghcup/env"

#for wallpapers
wally() {
       local image="$1"
       shift
       [[ ! -f "$image" ]] && image="$HOME/Pictures/Wallpapers/$image"
       ~/.config/scripts/wallpaper.sh "$image" "$@"
   }
#the command is wally image.png dark scheme-vibrant
