color0 #131315
color1 #ffb4ab
color2 #e3bbd7
color3 #c5c5d5
color4 #bfc5e8
color5 #e3bbd7
color6 #c5c5d5
color7 #e5e1e4
color8 #909098
color9 #ffb4ab
color10 #e3bbd7
color11 #c5c5d5
color12 #bfc5e8
color13 #e3bbd7
color14 #c5c5d5
color15 #e5e1e4

cursor                #e5e1e4
cursor_text_color     #131315
background            #131315
foreground            #e5e1e4
selection_foreground  #c7c5ce
selection_background  #46464d
url_color             #bfc5e8