# gtklock configuration
# https://github.com/jovanlanik/gtklock

[main]
# Style & layout
style = /home/kshinpad/.config/gtklock/style.css

# Modules (comment out if gtklock-playerctl-module is not installed)
modules = /usr/lib/gtklock/playerctl-module.so

# Clock & date format (strftime)
time-format = %H:%M
date-format = %A, %d %B

# Follow focus between monitors
follow-focus = false

# Hide the form after idle-timeout seconds of no input
idle-hide = true
idle-timeout = 15

# Start with the form hidden (reveal on any keypress)
start-hidden = true
